let camisasJson = [
  {
    id: 1,
    name: 'Real Madrid Home | 21/22',
    img: 'imagens/camisa1.png',
    imgB: 'imagens/camisa1Back.png',
    imgM: 'imagens/camisa1Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 2,
    name: 'Real Madrid Away | 21/22',
    img: 'imagens/camisa2.png',
    imgB: 'imagens/camisa2Back.png',
    imgM: 'imagens/camisa2Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 3,
    name: 'Real Madrid Goalkerper | 21/22',
    img: 'imagens/camisa3.png',
    imgB: 'imagens/camisa3Back.png',
    imgM: 'imagens/camisa3Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 4,
    name: 'Real Madrid Third | 21/22',
    img: 'imagens/camisa4.png',
    imgB: 'imagens/camisa4Back.png',
    imgM: 'imagens/camisa4Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 5,
    name: 'Real Madrid Home | 20/21',
    img: 'imagens/camisa5.png',
    imgB: 'imagens/camisa5Back.png',
    imgM: 'imagens/camisa5Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 6,
    name: 'Real Madrid Third | 20/21',
    img: 'imagens/camisa6.webp',
    imgB: 'imagens/camisa6Back.webp',
    imgM: 'imagens/camisa6Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 7,
    name: 'Real Madrid Goalkerper | 20/21',
    img: 'imagens/camisa7.png',
    imgB: 'imagens/camisa7Back.webp',
    imgM: 'imagens/camisa7Model.png',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 8,
    name: 'Real Madrid Away | 17/18',
    img: 'imagens/camisa8.png',
    imgB: 'imagens/camisa8Back.webp',
    imgM: 'imagens/camisa8Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 9,
    name: 'Real Madrid Home | 17/18',
    img: 'imagens/camisa9.png',
    imgB: 'imagens/camisa9Back.png',
    imgM: 'imagens/camisa9Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
  {
    id: 10,
    name: 'Real Madrid Third | 16/17',
    img: 'imagens/camisa10.png',
    imgB: 'imagens/camisa10Back.png',
    imgM: 'imagens/camisa10Model.jpg',
    price: 249.99,
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    model: ['Man', 'Women'],
  },
];
